version: '3.8'  

services:  
  app:  
    image: mcr.microsoft.com/dotnet/aspnet:7.0 # .NET runtime imajý  
    container_name: dotnet-app  
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "5000:5000" # Uygulamanýzýn dýþarýya açýlacaðý port  
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
      - REDIS_CONNECTION=redis:6379 # Redis baðlantý adresi  
    depends_on:  
      - redis # Redis servisini bekler  
    networks:  
      - app-network  

  redis:  
    image: redis:7.0 # Redis imajý  
    container_name: redis  
    ports:  
      - "6379:6379" # Redis'in dýþarýya açýlacaðý port  
    networks:  
      - app-network  
    volumes:  
      - redis-data:/data # Redis verilerini kalýcý hale getirmek için volume  

networks:  
  app-network:  
    driver: bridge  

volumes:  
  redis-data:  