version: '3.8'  

services:  
  app:  
    image: mcr.microsoft.com/dotnet/aspnet:7.0  
    container_name: dotnet-app  
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "5000:5000"  
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
      - REDIS_CONNECTION=redis:6379  
    depends_on:  
      - redis  
    networks:  
      - app-network  

  redis:  
    image: redis:7.0  
    container_name: redis  
    ports:  
      - "6379:6379"  
    networks:  
      - app-network  
    volumes:  
      - redis-data:/data  

networks:  
  app-network:  
    driver: bridge  

volumes:  
  redis-data: